### ISSUE TITLE
Is the client supposed to be executing the "shared_behavior::process_command"?

### ISSUE THREAD

**Issue by 00alia00** [naia-rs/naia-macroquad-example#1]
I noticed that if i ran two clients and the server that the clients would get out of sync with themselves and the other client. I tracked it down to line 96 in client/app.rs
```
ExampleActor::PointActor(actor) => {
     // By commenting this out, this code only runs on the server, so now all clients will agree on where they are 
     // otherwise the server executes the code, update the position and then the client does too (effectively desyncing)
     //  shared_behavior::process_command(&key_command, actor);
}
```

**Comment by naia-rs** [comment]
Yeah, the intent is that both the server and the client can run the same code when Pawns receive a Command (which you identified in line 96). A Pawn will process the same Command on both the client & the server, and reconcile state if they get out of sync. This allows the client to immediately respond to user actions, this important for "game-feel" in action games. This is naia's implementation of "client-side prediction" (look up that term if you're not familiar)
If you don't mind a delay to your input, just use Actors, not Pawns + Commands

**Comment by 00alia00** [comment]
Ah gotcha, thanks for the reply!
